## Container Settings
gmail:
  username:
  password:
  from: SCC
email:
  sender: SCC
  subject: Daily FCR Forecast and Graphs
  body: "Hello from GitHub Actions!\n\nHere are today's forecast and graphs. \n\nhttps://flare-forecast.org/flare-dashboard/fcre.html\n\nHave a wonderful day!\n\nBests,\nSCC and CIBR Team"
  attachments_web:
  attachments_local:
  recipients:
    - y.ku@ufl.edu
